### ISSUE TITLE
Importing Image Sequence Doesnt work anymore with Build 1584

### ISSUE THREAD

**Issue by MoonStar2D** [2d-inc/2D-Issues#3]
### prerequisites
1. a sequence of images is needed (you can use the attached slash fx)
[slash fx.zip](https://github.com/2d-inc/2D-Issues/files/1645070/slash.fx.zip)

### steps
1. drag and drop the image sequence from your desktop onto the assets panel in nima
2. from the popping up toast message click yes for "import as image sequence"

### issue
after a short while a new toast message appears that asset is being imported. However it takes ages I waited an hour for example and assets were not imported. 

### Workaround
If the user clicks on no for keep the sequence or images separated they are in fact imported in no time.

**Comment by luigi-rosso** [comment]
This should be fixed as of build 1590 which is up now. Feel free to close it if you can confirm it works for you @MoonStar2D.
